services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ../configs/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ../configs/caddy/site-data:/srv/site-data

volumes:
  caddy_data:
  caddy_config: