services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=568
      - PGID=568
    volumes:
      - /mnt/deadpool/media:/data:ro
      - /mnt/flash/configs/jellyfin:/config
    tmpfs:
      - /cache
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]