services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Europe/London
    ports:
      - 5055:5055
    volumes:
      - jellyseerr-data:/app/config
    restart: unless-stopped

volumes:
  jellyseerr-data: