services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    network_mode: host
    user: 568:568
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /mnt/deadpool/media:/data:ro
      - /mnt/flash/configs/jellyfin:/config
    tmpfs:
      - /cache
    devices:
      - /dev/dri:/dev/dri