services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      # DNS
      - 53:53/tcp
      - 53:53/udp
      # HTTP frontend
      - 8080:80
    environment:
      TZ: 'Europe/London'
      FTLCONF_dns_listeningMode: 'all'
    cap_add:
      - NET_ADMIN
    volumes:
      - pihole-data:/etc/pihole

volumes:
  pihole-data: