services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
      - ADVERTISE_IP=http://192.168.0.126:32400
      - VERSION=docker
      - PLEX_CLAIM=claim-ymhbxQ1mNKnNR1cJDQNF
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /mnt/deadpool/media:/data:ro
      - /mnt/flash/configs/plex:/config
    tmpfs:
      - /transcode
    devices:
      - /dev/dri:/dev/dri

volumes:
  plex_config: