services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400   #Default port
      - 32469:32469   #SSL port
      - 1900:1900/udp   #DLNA server
      - 32410:32410/udp   #GDM network discovery
      - 32412:32412/udp   #GDM network discovery
      - 32413:32413/udp   #GDM network discovery
      - 32414:32414/udp   #GDM network discovery
    environment:
      - TZ=Europe/London
      - ADVERTISE_IP=http://192.168.0.126:32400
      - PLEX_CLAIM=claim-ymhbxQ1mNKnNR1cJDQNF
      - NVIDIA_VISIBLE_DEVICES=all
    hostname: luthor.bi-frost
    volumes:
      - /media:/media
      - plex_config:/config
    tmpfs:
      - /transcode

volumes:
  plex_config: