services:
  portainer_agent:
    container_name: protainer_agent
    image: portainer/agent:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes