services:
  portainer_server:
    container_name: portainer_server
    image: portainer/portainer-ee:latest
    command: -H tcp://portainer_agent:9001 --tlsskipverify
    restart: always
    ports:
      - 9443:9000
    volumes:
      - portainer-data:/data

volumes:
  portainer-data: