services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - TS_AUTHKEY=""
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN